import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { Suspense } from "react";
import Loading from "./loading";
import StoreProvider from "./StoreProvider";
import AuthProvider from "./_components/AuthProvider";

export const metadata: Metadata = {
  title: "Kitsune's Links",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-dvh flex flex-col">
        <AuthProvider>
          <StoreProvider>
            <Header />

            <Suspense fallback={<Loading />}>
              <main className="flex-1 flex flex-col">{children}</main>
            </Suspense>

            <Footer />
          </StoreProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
