import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";

export const metadata: Metadata = {
  title: "karrtka",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-dvh flex flex-col">
        <Header />

        <main className="flex-1 mx-auto w-xl">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
